server {
    listen 80;
    server_name vpn.spraxxx.net;

    # Static files (client configs + QR)
    location /clients/ {
        alias /var/www/wg/clients/;
        autoindex on;
        add_header Cache-Control "no-store";
    }

    # API
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}